name=Fusion
version=1.2.12
author=xioTechnologies
maintainer=xioTechnologies
sentence=Sensor Fusion library for Inertial Measurement Units
paragraph=Fusion is a sensor fusion library for Inertial Measurement Units (IMUs), optimised for embedded systems. Fusion is a C library but is also available as the Python package, imufusion. Two example Python scripts, simple_example.py and advanced_example.py are provided with example sensor data to demonstrate use of the package.
category=Sensors
url=https://github.com/xioTechnologies/Fusion
architectures=*
includes=Fusion.h
