import numpy as np

ALIGNMENT_PXPYPZ: int
ALIGNMENT_PXNZPY: int
ALIGNMENT_PXNYNZ: int
ALIGNMENT_PXPZNY: int
ALIGNMENT_NXPYNZ: int
ALIGNMENT_NXPZPY: int
ALIGNMENT_NXNYPZ: int
ALIGNMENT_NXNZNY: int
ALIGNMENT_PYNXPZ: int
ALIGNMENT_PYNZNX: int
ALIGNMENT_PYPXNZ: int
ALIGNMENT_PYPZPX: int
ALIGNMENT_NYPXPZ: int
ALIGNMENT_NYNZPX: int
ALIGNMENT_NYNXNZ: int
ALIGNMENT_NYPZNX: int
ALIGNMENT_PZPYNX: int
ALIGNMENT_PZPXPY: int
ALIGNMENT_PZNYPX: int
ALIGNMENT_PZNXNY: int
ALIGNMENT_NZPYPX: int
ALIGNMENT_NZNXPY: int
ALIGNMENT_NZNYNX: int
ALIGNMENT_NZPXNY: int
CONVENTION_NWU: int
CONVENTION_ENU: int
CONVENTION_NED: int

# compass_methods
def compass(accelerometer: np.ndarray, magnetometer: np.ndarray, convention: int = ...) -> float: ...

# convert_methods
def quaternion_to_matrix(quaternion: np.ndarray) -> np.ndarray: ...
def quaternion_to_euler(quaternion: np.ndarray) -> np.ndarray: ...

# model_methods
def model_inertial(
    uncalibrated: np.ndarray,
    misalignment: np.ndarray = ...,
    sensitivity: np.ndarray = ...,
    offset: np.ndarray = ...,
) -> np.ndarray: ...
def model_magnetic(
    uncalibrated: np.ndarray,
    soft_iron_matrix: np.ndarray = ...,
    hard_iron_offset: np.ndarray = ...,
) -> np.ndarray: ...

# remap_methods
def remap(sensor: np.ndarray, alignment: int) -> np.ndarray: ...

# ahrs_object
class Ahrs:
    def __init__(self) -> None: ...
    @property
    def settings(self) -> None: ...
    @settings.setter
    def settings(self, value: AhrsSettings) -> None: ...
    @property
    def sample_period(self) -> None: ...
    @sample_period.setter
    def sample_period(self, value: float) -> None: ...
    @property
    def quaternion(self) -> np.ndarray: ...
    @quaternion.setter
    def quaternion(self, value: np.ndarray) -> None: ...
    @property
    def gravity(self) -> np.ndarray: ...
    @property
    def linear_acceleration(self) -> np.ndarray: ...
    @property
    def earth_acceleration(self) -> np.ndarray: ...
    @property
    def internal_states(self) -> AhrsInternalStates: ...
    @property
    def flags(self) -> AhrsFlags: ...
    @property
    def heading(self) -> None: ...
    @heading.setter
    def heading(self, value: float) -> None: ...
    def reset(self) -> None: ...
    def update(self, gyroscope: np.ndarray, accelerometer: np.ndarray, magnetometer: np.ndarray) -> None: ...
    def update_no_magnetometer(self, gyroscope: np.ndarray, accelerometer: np.ndarray) -> None: ...
    def update_external_heading(self, gyroscope: np.ndarray, accelerometer: np.ndarray, heading: float) -> None: ...

# ahrs_flags_object
class AhrsFlags:
    @property
    def initialising(self) -> bool: ...
    @property
    def angular_rate_recovery(self) -> bool: ...
    @property
    def acceleration_recovery(self) -> bool: ...
    @property
    def magnetic_recovery(self) -> bool: ...

# ahrs_internal_states_object
class AhrsInternalStates:
    @property
    def acceleration_error(self) -> float: ...
    @property
    def accelerometer_ignored(self) -> bool: ...
    @property
    def acceleration_recovery_trigger(self) -> float: ...
    @property
    def magnetic_error(self) -> float: ...
    @property
    def magnetometer_ignored(self) -> bool: ...
    @property
    def magnetic_recovery_trigger(self) -> float: ...

# ahrs_settings_object
class AhrsSettings:
    def __init__(
        self,
        convention: int = ...,
        gain: float = ...,
        gyroscope_range: float = ...,
        acceleration_rejection: float = ...,
        magnetic_rejection: float = ...,
        recovery_trigger_period: int = ...,
    ) -> None: ...
    @property
    def convention(self) -> int: ...
    @convention.setter
    def convention(self, value: int) -> None: ...
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float) -> None: ...
    @property
    def gyroscope_range(self) -> float: ...
    @gyroscope_range.setter
    def gyroscope_range(self, value: float) -> None: ...
    @property
    def acceleration_rejection(self) -> float: ...
    @acceleration_rejection.setter
    def acceleration_rejection(self, value: float) -> None: ...
    @property
    def magnetic_rejection(self) -> float: ...
    @magnetic_rejection.setter
    def magnetic_rejection(self, value: float) -> None: ...
    @property
    def recovery_trigger_period(self) -> int: ...
    @recovery_trigger_period.setter
    def recovery_trigger_period(self, value: int) -> None: ...

# bias_object
class Bias:
    def __init__(self) -> None: ...
    @property
    def settings(self) -> None: ...
    @settings.setter
    def settings(self, value: BiasSettings) -> None: ...
    def update(self, gyroscope: np.ndarray) -> np.ndarray: ...

# bias_settings_object
class BiasSettings:
    def __init__(
        self,
        sample_rate: float = ...,
        stationary_period: float = ...,
        stationary_threshold: float = ...,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, value: float) -> None: ...
    @property
    def stationary_threshold(self) -> float: ...
    @stationary_threshold.setter
    def stationary_threshold(self, value: float) -> None: ...
    @property
    def stationary_period(self) -> float: ...
    @stationary_period.setter
    def stationary_period(self, value: float) -> None: ...
