import numpy as np

ALIGNMENT_PXPYPZ: int
ALIGNMENT_PXNZPY: int
ALIGNMENT_PXNYNZ: int
ALIGNMENT_PXPZNY: int
ALIGNMENT_NXPYNZ: int
ALIGNMENT_NXPZPY: int
ALIGNMENT_NXNYPZ: int
ALIGNMENT_NXNZNY: int
ALIGNMENT_PYNXPZ: int
ALIGNMENT_PYNZNX: int
ALIGNMENT_PYPXNZ: int
ALIGNMENT_PYPZPX: int
ALIGNMENT_NYPXPZ: int
ALIGNMENT_NYNZPX: int
ALIGNMENT_NYNXNZ: int
ALIGNMENT_NYPZNX: int
ALIGNMENT_PZPYNX: int
ALIGNMENT_PZPXPY: int
ALIGNMENT_PZNYPX: int
ALIGNMENT_PZNXNY: int
ALIGNMENT_NZPYPX: int
ALIGNMENT_NZNXPY: int
ALIGNMENT_NZNYNX: int
ALIGNMENT_NZPXNY: int
CONVENTION_NWU: int
CONVENTION_ENU: int
CONVENTION_NED: int
PROGRESS_STATUS_NOT_STARTED: int
PROGRESS_STATUS_IN_PROGRESS: int
PROGRESS_STATUS_COMPLETE: int
PROGRESS_STATUS_FAILED: int
PROGRESS_STATUS_ABORTED: int

# compass_methods
def compass(accelerometer: np.ndarray, magnetometer: np.ndarray, convention: int = ...) -> float: ...

# convert_methods
def quaternion_to_matrix(quaternion: np.ndarray) -> np.ndarray: ...
def quaternion_to_euler(quaternion: np.ndarray) -> np.ndarray: ...

# model_methods
def model_inertial(
    uncalibrated: np.ndarray,
    misalignment: np.ndarray = ...,
    sensitivity: np.ndarray = ...,
    offset: np.ndarray = ...,
) -> np.ndarray: ...
def model_magnetic(
    uncalibrated: np.ndarray,
    soft_iron_matrix: np.ndarray = ...,
    hard_iron_offset: np.ndarray = ...,
) -> np.ndarray: ...

# progress_methods
def progress_status_to_string(status: int) -> str: ...

# remap_methods
def remap(sensor: np.ndarray, alignment: int) -> np.ndarray: ...

# ahrs_object
class Ahrs:
    def __init__(self) -> None: ...
    def set_settings(self, settings: AhrsSettings) -> None: ...
    def set_sample_period(self, sample_period: float) -> None: ...
    def restart(self) -> None: ...
    def update(self, gyroscope: np.ndarray, accelerometer: np.ndarray, magnetometer: np.ndarray) -> None: ...
    def update_no_magnetometer(self, gyroscope: np.ndarray, accelerometer: np.ndarray) -> None: ...
    def update_external_heading(self, gyroscope: np.ndarray, accelerometer: np.ndarray, heading: float) -> None: ...
    def get_quaternion(self) -> np.ndarray: ...
    def set_quaternion(self, quaternion: np.ndarray) -> None: ...
    def get_gravity(self) -> np.ndarray: ...
    def get_linear_acceleration(self) -> np.ndarray: ...
    def get_earth_acceleration(self) -> np.ndarray: ...
    def get_internal_states(self) -> AhrsInternalStates: ...
    def get_flags(self) -> AhrsFlags: ...
    def set_heading(self, heading: float) -> None: ...

# ahrs_flags_object
class AhrsFlags:
    @property
    def startup(self) -> bool: ...
    @property
    def angular_rate_recovery(self) -> bool: ...
    @property
    def acceleration_recovery(self) -> bool: ...
    @property
    def magnetic_recovery(self) -> bool: ...

# ahrs_internal_states_object
class AhrsInternalStates:
    @property
    def acceleration_error(self) -> float: ...
    @property
    def accelerometer_ignored(self) -> bool: ...
    @property
    def acceleration_recovery_trigger(self) -> float: ...
    @property
    def magnetic_error(self) -> float: ...
    @property
    def magnetometer_ignored(self) -> bool: ...
    @property
    def magnetic_recovery_trigger(self) -> float: ...

# ahrs_settings_object
class AhrsSettings:
    def __init__(
        self,
        sample_rate: float = ...,
        convention: int = ...,
        gain: float = ...,
        gyroscope_range: float = ...,
        acceleration_rejection: float = ...,
        magnetic_rejection: float = ...,
        rejection_timeout: float = ...,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, value: float) -> None: ...
    @property
    def convention(self) -> int: ...
    @convention.setter
    def convention(self, value: int) -> None: ...
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float) -> None: ...
    @property
    def gyroscope_range(self) -> float: ...
    @gyroscope_range.setter
    def gyroscope_range(self, value: float) -> None: ...
    @property
    def acceleration_rejection(self) -> float: ...
    @acceleration_rejection.setter
    def acceleration_rejection(self, value: float) -> None: ...
    @property
    def magnetic_rejection(self) -> float: ...
    @magnetic_rejection.setter
    def magnetic_rejection(self, value: float) -> None: ...
    @property
    def rejection_timeout(self) -> float: ...
    @rejection_timeout.setter
    def rejection_timeout(self, value: float) -> None: ...

# bias_object
class Bias:
    def __init__(self) -> None: ...
    def set_settings(self, settings: BiasSettings) -> None: ...
    def update(self, gyroscope: np.ndarray) -> None: ...
    def get_corrected_gyroscope(self) -> np.ndarray: ...
    def get_offset(self) -> np.ndarray: ...
    def set_offset(self, offset: np.ndarray) -> None: ...
    def start(self) -> None: ...
    def get_progress(self) -> Progress: ...
    def complete(self) -> None: ...
    def completed(self) -> bool: ...
    def abort(self) -> None: ...

# bias_settings_object
class BiasSettings:
    def __init__(
        self,
        sample_rate: float = ...,
        duration: float = ...,
        threshold: float = ...,
        continuous: bool = ...,
        holdoff: float = ...,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, value: float) -> None: ...
    @property
    def duration(self) -> float: ...
    @duration.setter
    def duration(self, value: float) -> None: ...
    @property
    def threshold(self) -> float: ...
    @threshold.setter
    def threshold(self, value: float) -> None: ...
    @property
    def continuous(self) -> bool: ...
    @continuous.setter
    def continuous(self, value: bool) -> None: ...
    @property
    def holdoff(self) -> float: ...
    @holdoff.setter
    def holdoff(self, value: float) -> None: ...

# hard_iron_object
class HardIron:
    def __init__(self) -> None: ...
    def set_settings(self, settings: HardIronSettings) -> None: ...
    def update(self, magnetometer: np.ndarray) -> None: ...
    def get_corrected_magnetometer(self) -> np.ndarray: ...
    def get_offset(self) -> np.ndarray: ...
    def set_offset(self, offset: np.ndarray) -> None: ...
    def start(self) -> None: ...
    def get_progress(self) -> Progress: ...
    def complete(self) -> None: ...
    def completed(self) -> bool: ...
    def abort(self) -> None: ...
    def get_samples(self) -> np.ndarray: ...
    @staticmethod
    def solve(samples: np.ndarray) -> np.ndarray: ...

# hard_iron_settings_object
class HardIronSettings:
    def __init__(
        self,
        sample_rate: float = ...,
        timeout: float = ...,
        intensity: float = ...,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, value: float) -> None: ...
    @property
    def timeout(self) -> float: ...
    @timeout.setter
    def timeout(self, value: float) -> None: ...
    @property
    def intensity(self) -> float: ...
    @intensity.setter
    def intensity(self, value: float) -> None: ...

# progress_object
class Progress:
    @property
    def status(self) -> int: ...
    @property
    def percentage(self) -> int: ...
