import numpy as np

ALIGNMENT_PXPYPZ: int
ALIGNMENT_PXPZNY: int
ALIGNMENT_PXNZPY: int
ALIGNMENT_PXNYNZ: int
ALIGNMENT_PYPXNZ: int
ALIGNMENT_PYPZPX: int
ALIGNMENT_PYNZNX: int
ALIGNMENT_PYNXPZ: int
ALIGNMENT_PZPXPY: int
ALIGNMENT_PZPYNX: int
ALIGNMENT_PZNYPX: int
ALIGNMENT_PZNXNY: int
ALIGNMENT_NZPXNY: int
ALIGNMENT_NZPYPX: int
ALIGNMENT_NZNYNX: int
ALIGNMENT_NZNXPY: int
ALIGNMENT_NYPXPZ: int
ALIGNMENT_NYPZNX: int
ALIGNMENT_NYNZPX: int
ALIGNMENT_NYNXNZ: int
ALIGNMENT_NXPYNZ: int
ALIGNMENT_NXPZPY: int
ALIGNMENT_NXNZNY: int
ALIGNMENT_NXNYPZ: int
CONVENTION_NWU: int
CONVENTION_ENU: int
CONVENTION_NED: int

# compass_methods
def compass(accelerometer: np.ndarray, magnetometer: np.ndarray, convention: int = ...) -> float: ...

# convention_methods
def convention_to_string(convention: int) -> str: ...

# convert_methods
def quaternion_to_matrix(quaternion: np.ndarray) -> np.ndarray: ...
def quaternion_to_euler(quaternion: np.ndarray) -> np.ndarray: ...

# model_methods
def model_inertial(
    uncalibrated: np.ndarray,
    misalignment: np.ndarray = ...,
    sensitivity: np.ndarray = ...,
    offset: np.ndarray = ...,
) -> np.ndarray: ...
def model_magnetic(
    uncalibrated: np.ndarray,
    soft_iron_matrix: np.ndarray = ...,
    hard_iron_offset: np.ndarray = ...,
) -> np.ndarray: ...

# remap_methods
def remap(sensor: np.ndarray, alignment: int) -> np.ndarray: ...
def alignment_to_string(alignment: int) -> str: ...

# ahrs_object
class Ahrs:
    def __init__(self) -> None: ...
    def set_settings(self, settings: AhrsSettings) -> Ahrs: ...
    def set_sample_period(self, sample_period: float) -> Ahrs: ...
    def restart(self) -> Ahrs: ...
    def skip_startup(self) -> Ahrs: ...
    def update(self, gyroscope: np.ndarray, accelerometer: np.ndarray, magnetometer: np.ndarray) -> Ahrs: ...
    def update_no_magnetometer(self, gyroscope: np.ndarray, accelerometer: np.ndarray) -> Ahrs: ...
    def update_external_heading(self, gyroscope: np.ndarray, accelerometer: np.ndarray, heading: float) -> Ahrs: ...
    def get_quaternion(self) -> np.ndarray: ...
    def set_quaternion(self, quaternion: np.ndarray) -> Ahrs: ...
    def get_gravity(self) -> np.ndarray: ...
    def get_linear_acceleration(self) -> np.ndarray: ...
    def get_earth_acceleration(self) -> np.ndarray: ...
    def get_internal_states(self) -> AhrsInternalStates: ...
    def get_flags(self) -> AhrsFlags: ...
    def set_heading(self, heading: float) -> Ahrs: ...

# ahrs_flags_object
class AhrsFlags:
    @property
    def startup(self) -> bool: ...
    @property
    def overrange_recovery(self) -> bool: ...
    @property
    def acceleration_recovery(self) -> bool: ...
    @property
    def magnetic_recovery(self) -> bool: ...

# ahrs_internal_states_object
class AhrsInternalStates:
    @property
    def acceleration_error(self) -> float: ...
    @property
    def accelerometer_ignored(self) -> bool: ...
    @property
    def acceleration_recovery_trigger(self) -> float: ...
    @property
    def magnetic_error(self) -> float: ...
    @property
    def magnetometer_ignored(self) -> bool: ...
    @property
    def magnetic_recovery_trigger(self) -> float: ...

# ahrs_settings_object
class AhrsSettings:
    def __init__(
        self,
        sample_rate: float = ...,
        convention: int = ...,
        gain: float = ...,
        gyroscope_range: float = ...,
        acceleration_rejection: float = ...,
        magnetic_rejection: float = ...,
        rejection_timeout: float = ...,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, value: float) -> None: ...
    @property
    def convention(self) -> int: ...
    @convention.setter
    def convention(self, value: int) -> None: ...
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float) -> None: ...
    @property
    def gyroscope_range(self) -> float: ...
    @gyroscope_range.setter
    def gyroscope_range(self, value: float) -> None: ...
    @property
    def acceleration_rejection(self) -> float: ...
    @acceleration_rejection.setter
    def acceleration_rejection(self, value: float) -> None: ...
    @property
    def magnetic_rejection(self) -> float: ...
    @magnetic_rejection.setter
    def magnetic_rejection(self, value: float) -> None: ...
    @property
    def rejection_timeout(self) -> float: ...
    @rejection_timeout.setter
    def rejection_timeout(self, value: float) -> None: ...

# bias_object
class Bias:
    def __init__(self) -> None: ...
    def set_settings(self, settings: BiasSettings) -> Bias: ...
    def update(self, gyroscope: np.ndarray) -> np.ndarray: ...
    def get_offset(self) -> np.ndarray: ...
    def set_offset(self, offset: np.ndarray) -> Bias: ...

# bias_settings_object
class BiasSettings:
    def __init__(
        self,
        sample_rate: float = ...,
        stationary_threshold: float = ...,
        stationary_period: float = ...,
    ) -> None: ...
    @property
    def sample_rate(self) -> float: ...
    @sample_rate.setter
    def sample_rate(self, value: float) -> None: ...
    @property
    def stationary_threshold(self) -> float: ...
    @stationary_threshold.setter
    def stationary_threshold(self, value: float) -> None: ...
    @property
    def stationary_period(self) -> float: ...
    @stationary_period.setter
    def stationary_period(self, value: float) -> None: ...
